#!/bin/bash
while true; 
do 
echo "Starting Server"
    if siriproxy-expr server; then
       echo "[Info - SiriProxy] Pausing for 30 seconds" 
       sleep 30
    else
      echo "[Warning - Crash - SiriProxy] Crashed! Restarting in 2 sec!"
      sleep 1
    fi

done
