<?php
	/******************************************************************
	 * Project: The Three Little Pigs - Siri Proxy | Web Interface
	 * Project start date: 21-01-2012
	 * Author: Wouter De Schuyter
	 * Website: www.wouterds.be
	 * E: info[@]wouterds[.]be
	 * T: www.twitter.com/wouterds
	 *
	 * File: clients.php
     * Last update: 22-02-2012
	******************************************************************/

	echo '<h1>Clients</h1><p>Clients are people that were able to generate an assistant. Once you were able to generate an assistant you will be able to connect with this server as long as the maximum connections are not reached. If you\'re not on the list, than you haven\'t got an assistant generated by one of the keys on this server. The fields are pretty much self explanatory so I won\'t explain them fully.</p>';

	$websiteProperty = new WebsiteProperty();
            
	$pid = $_GET['page-id'];
	
	if(empty($pid)) { $pid = 1; }
	
    $sql = "SELECT id FROM clients ORDER BY id DESC ";
    $dataQuery = mysql_query($sql);
	$rowsQuery = mysql_num_rows($dataQuery);
	
	$lastPage = ceil($rowsQuery/$websiteProperty->getProperty('max_client_entries_per_page'));
	
	if($pid < 1) { 
		$pid = 1;
	}
	elseif($pid > $lastPage) {
		$pid = $lastPage;
	}
    
	$max = 'LIMIT ' . (($pid - 1) * $websiteProperty->getProperty('max_client_entries_per_page')) .',' .$websiteProperty->getProperty('max_client_entries_per_page'); 
	
	

	
	echo "<div id='pagination'>";
		
		if ($pid > 1) 

 {

 echo " <a href='?page=" . $_GET['page'] . "&amp;page-id=1#pagination'>&lt;&lt;</a> ";

 echo " ";

 $previous = $pid-1;

 echo " <a href='?page=" . $_GET['page'] . "&amp;page-id=$previous#pagination'>&lt;</a> ";

 } 


			if(($pid - 3) > 0) {
				$i = $pid - 3;
			}
			else {
				$i = 1;
			}
			if(($pid + 3) <= $lastPage) {
				$mPage = $pid + 3;
			}
			else {
				$mPage = $lastPage;
			}
			while($i <= $mPage) {
				echo '<a href="?page=' . $_GET['page'] . '&amp;page-id=' . $i . '#pagination"';
				if($pid == $i) {
					echo ' class="current"';
				}
				echo '>' . $i . '</a>';
				$i++;
			}


 //This does the same as above, only checking if we are on the last page, and then generating the Next and Last links

 if ($pid !== $lastPage) 

 {

 $next = $pid+1;

 echo " <a href='?page=" . $_GET['page'] . "&amp;page-id=$next#pagination'>&gt;</a> ";

 echo " ";

 echo " <a href='?page=" . $_GET['page'] . "&amp;page-id=$lastPage#pagination'>&gt;&gt;</a>";

 } 
   
   echo ' </div>';
   
   ?>
    <table width="100%">
        <tr>
            <th>First Name</th>
            <th>Nickname</th>
            <th>Device</th>
            <th>Valid</th>
            <th>Date Added</th>
        </tr>
		<?php
	
	
	$sql = "SELECT nickname, fname, date_added, valid, id FROM clients ORDER BY apple_account_id ASC";
        $sql1 = "SELECT device_type FROM assistants GROUP BY client_apple_account_id ORDER BY client_apple_account_id ASC";
    $dataQuery = mysql_query($sql) or die(mysql_error());
    $dataQuery1 = mysql_query($sql1) or die(mysql_error());
	
	
	while($data = mysql_fetch_assoc($dataQuery) and $data1 = mysql_fetch_assoc($dataQuery1)) {
		echo '<tr>';
		echo '<td>';
		if($data['fname'] == "NA") {
			echo '<p class="notification red minimal">n/a</p>';
		}
		else {
			echo $data['fname'];
		}
		echo '</td>';
		echo '<td>';
		if($data['nickname'] == "NA") {
			echo '<p class="notification red minimal">n/a</p>';
		}
		else {
			echo $data['nickname'];
		}
		echo '</td>';
                echo '<td>' . $data1['device_type'] . '</td>';
		echo '<td>';
		echo '<p class="notification ';
		if($data['valid'] == 'True') {
			echo 'green';
		}
		else {
			echo 'red';
		}
		echo ' minimal">' . $data['valid'];
		echo '</td>';
		echo '<td>' . $data['date_added'] . '</td>';
		echo '</tr>';
	}
	
	?>
	</table>
    <?php
	
	
	echo "<div id='pagination'>";
		
		if ($pid > 1) 

 {

 echo " <a href='?page=" . $_GET['page'] . "&amp;page-id=1#pagination'>&lt;&lt;</a> ";

 echo " ";

 $previous = $pid-1;

 echo " <a href='?page=" . $_GET['page'] . "&amp;page-id=$previous#pagination'>&lt;</a> ";

 } 


			if(($pid - 3) > 0) {
				$i = $pid - 3;
			}
			else {
				$i = 1;
			}
			if(($pid + 3) <= $lastPage) {
				$mPage = $pid + 3;
			}
			else {
				$mPage = $lastPage;
			}
			while($i <= $mPage) {
				echo '<a href="?page=' . $_GET['page'] . '&amp;page-id=' . $i . '#pagination"';
				if($pid == $i) {
					echo ' class="current"';
				}
				echo '>' . $i . '</a>';
				$i++;
			}


 //This does the same as above, only checking if we are on the last page, and then generating the Next and Last links

 if ($pid !== $lastPage) 

 {

 $next = $pid+1;

 echo " <a href='?page=" . $_GET['page'] . "&amp;page-id=$next#pagination'>&gt;</a> ";

 echo " ";

 echo " <a href='?page=" . $_GET['page'] . "&amp;page-id=$lastPage#pagination'>&gt;&gt;</a>";

 } 
   
   echo ' </div>';
        ?>
		<h2 id="search">Check if you're on the list</h2>
        <?php
		
			if($_SERVER['REQUEST_METHOD'] == "POST") {
				$search = $_POST['search'];
				
				if(strlen($search) == 0) {
					echo '<p class="notification red">Please enter a name or nickname.</p>';
				}
				else {
					$sql = "SELECT * FROM clients WHERE nickname LIKE '%" . mysql_real_escape_string($search) . "%' OR fname LIKE '%" . mysql_real_escape_string($search) . "%'"; 
					$query = mysql_query($sql);
					if($query) {
						if(mysql_num_rows($query) > 0) {
							echo '<p class="notification green">We have found one or more results, you can see them in the list below.</p>';
							$resultsFound = true;
							
						}
						else {
							echo '<p class="notification red">We couldn\'t find this nickname or first name in the database.<br />Make sure you didn\'t made spelling mistakes.<p>';
						}
					}
					else {
						echo '<p class="notification red">Query error: ' . mysql_error() . '</p>';
					}
				}
			}
		?>
        <form class="styled" action="#search" method="post">
   				<label style="width: 180px;">First name or nickname</label>
   				<input type="text" name="search" />
                <input type="submit" value="Search" style="margin-left: 25px;"/>
        </form>
        
        
        
							
			<?php
			
			if($resultsFound) {				?>
    <table width="100%">
        <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Nickname</th>
            <th>Valid</th>
            <th>Date Added</th>
        </tr>
		<?php
	
	
	
	while($data = mysql_fetch_assoc($query)) {
		echo '<tr>';
		echo '<td>' . $data['id'] . '</td>';
		echo '<td>';
		if($data['fname'] == "NA") {
			echo '<p class="notification red minimal">n/a</p>';
		}
		else {
			echo $data['fname'];
		}
		echo '</td>';
		echo '<td>';
		if($data['nickname'] == "NA") {
			echo '<p class="notification red minimal">n/a</p>';
		}
		else {
			echo $data['nickname'];
		}
		echo '</td>';
		echo '<td>';
		echo '<p class="notification ';
		if($data['valid'] == 'True') {
			echo 'green';
		}
		else {
			echo 'red';
		}
		echo ' minimal">' . $data['valid'];
		echo '</td>';
		echo '<td>' . $data['date_added'] . '</td>';
		echo '</tr>';
	}
	
	?>
	</table>
    <?php
			}
			
			?>